#!/bin/bash

source $HOME/.bash_profile

CURL=/usr/bin/curl
SLEEP=/bin/sleep
BASH=/bin/bash

$CURL -s http://localhost:8983/solr/placenames/update --data '<delete><query>*:*</query></delete>' -H 'Content-type:text/xml; charset=utf-8' > /dev/null
$CURL -s http://localhost:8983/solr/placenames/update --data '<commit/>' -H 'Content-type:text/xml; charset=utf-8' > /dev/null
$SLEEP 1m
$BASH $HOME/gazetteer/deploy/schedule_provisioning