#!/bin/bash

DIRECTORY=gazetteer
SOLR_SANS_VERSION=solr
SOLR_VER=8.5.1
SOLR=solr-$SOLR_VER
SOLR_ZIP=$SOLR.zip
SOLR_HOME=$HOME/$SOLR
SOLR_DATA=$HOME/solr-data/data
# PROVISION_PROG=wfsToSolr
PROVISION_PROG=postgres/pgToSolr
# While testing use a file until we are sure it works and then do it direct off the service
# PROVISION_PROG=wfsFileToSolr

SOLR_ARCHIVE=$SOLR_HOME.zip
COMMAND=$DIRECTORY/deploy/install_solr.sh
INSTALL_SERVICE_COMMAND="gazetteer/deploy/install_solr.sh solr-$SOLR_VER.zip -u $LOGNAME -i $HOME -d $HOME/solr-data"

# Download
cd $HOME

if [ ! -d $SOLR ]; then
   echo "No SOLR installed"
   if [ ! -f $SOLR_ZIP ]; then
      echo "Fetching SOLR zip..."
      /usr/bin/wget http://mirror.intergrid.com.au/apache/lucene/solr/$SOLR_VER/$SOLR.zip
   fi
   echo "Unzipping SOLR"
   /usr/bin/unzip $SOLR.zip
fi

if [ ! -L $SOLR_SANS_VERSION ]; then
   ln -s $SOLR $SOLR_SANS_VERSION
fi

# Set up data
if [ ! -d $DIRECTORY ]; then
  echo "Fetching gazetteer project"
  git clone https://github.com/Tomella/$DIRECTORY.git
  cd $DIRECTORY
  echo "NPM install"
  npm install
else
  echo "Updating gazetteer from git and doing an NPM update..."
  cd $DIRECTORY
  git pull
  npm update
fi

# Does the data directory exist?
if [ ! -d $SOLR_DATA ]; then
   echo "Making Solr data directory..."
   mkdir -p $SOLR_DATA
fi

cp -f $HOME/$DIRECTORY/deploy/solr.xml $SOLR_DATA

# Set up service and get it running
if [ ! -f /etc/init.d/solr ]; then
  echo "Adding the Solr service to init scripts"
  echo  $INSTALL_SERVICE_COMMAND
  cd $HOME
  sudo bash $INSTALL_SERVICE_COMMAND
fi

sudo chkconfig --level 345 solr on
echo "Starting solr and sleeping..."
sleep 5s
sudo service solr restart


# Do we need rebuild the data?
if [ ! -d $SOLR_HOME/server/solr/placenames ]; then
  echo "Copying placenames config to Solr server"
  # Start loading data
  # cp -rf deploy/placenames $SOLR_HOME/server/solr
  cd $SOLR_HOME
  bin/solr create -c placenames -d $HOME/gazetteer/deploy/placenames/conf
  cd $HOME/$DIRECTORY/source
  node $PROVISION_PROG
  # Not sure if it will pick it up dynamically so try a restart to begin with.
  # sudo service solr restart
fi


echo 'Installation complete'