#!/bin/bash

DIRECTORY=gazetteer
SOLR_VER=6.3.0
SOLR=solr-$SOLR_VER
SOLR_ZIP=$SOLR.zip
SOLR_HOME=$HOME/$SOLR
SOLR_DATA=/home/ec2-user/solr-data
PROVISION_PROG=wfsToSolr
# While testing use a file until we are sure it works and then do it direct off the service
# PROVISION_PROG=wfsFileToSolr

SOLR_ARCHIVE=$SOLR_HOME.zip
COMMAND=$DIRECTORY/deploy/install_solr.sh
INSTALL_SERVICE_COMMAND="gazetteer/deploy/install_solr.sh solr-6.3.0.zip -u ec2-user -i /home/ec2-user -d /home/ec2-user/solr-data"

# Download
cd $HOME

if [ ! -d $SOLR ]; then
   echo "No SOLR installed"
   if [ ! -f $SOLR_ZIP ]; then
      echo "Fetching SOLR zip..."
      /usr/bin/wget http://mirror.intergrid.com.au/apache/lucene/solr/$SOLR_VER/$SOLR.zip
   fi
   echo "Unzipping SOLR"
   /usr/bin/unzip $SOLR.zip
fi

# Set up data
if [ ! -d $DIRECTORY ]; then
  echo "Fetching gazetteer project"
  git clone https://github.com/Tomella/$DIRECTORY.git
  cd $DIRECTORY
  echo "NPM install"
  npm install
else
  echo "Updating gazetteer from git and doing an NPM update..."
  cd $DIRECTORY
  git pull
  npm update
fi

# Set up proxying for select if there is an Apache config
if [ -d /etc/httpd/conf.d ]; then
  if [ ! -f /etc/httpd/conf.d/gazetteer.conf ]; then
    echo "Setting up Apache proxy"
    sudo cp $HOME/$DIRECTORY/deploy/gazetteer.conf /etc/httpd/conf.d
    sudo service httpd restart
  fi
else
  echo "No Apache installed so bypassing proxying"
fi

# Set up service and get it running
if [ ! -f /etc/init.d/solr ]; then
  echo "Adding the Solr service to init scripts"
  echo  $INSTALL_SERVICE_COMMAND
  cd $HOME
  chmod +x $COMMAND
  sudo $INSTALL_SERVICE_COMMAND
fi

sudo chkconfig --level 345 solr on
sudo service solr restart

# Do we need rebuild the data?
if [ ! -d $SOLR_HOME/server/solr/placenames ]; then
  echo "Copying placenames config to Solr server"
  # Start loading data
  # cp -rf deploy/placenames $SOLR_HOME/server/solr
  cd $SOLR_HOME
  bin/solr create -c placenames -d /home/ec2-user/gazetteer/deploy/placenames/conf
  cd $HOME/$DIRECTORY/source
  node $PROVISION_PROG
  # Not sure if it will pick it up dynamically so try a restart to begin with.
  # sudo service solr restart
fi


echo 'Installation complete'