#!/bin/sh
#
# chkconfig: 2345 90 60
#
# This script will launch Solr in a mode that will automatically respawn if it
# crashes. Output will be sent to /var/log/solr/solr.log. A PID file will be
# created in the standard location.
PROG="solr"
PIDFILE=/var/run/$PROG.pid
. /etc/init.d/functions

start () {
    echo -n "Starting solr..."

    # Start daemon
    daemon --chdir='/home/ec2-user/solr-6.3.0' --command "bin/solr start" --respawn --output=/var/log/$PROG/$PROG.log --name=$PROG --verbose

    RETVAL=$?
    if [ $RETVAL = 0 ]
    then
        echo "done."
    else
        echo "failed. See error code for more information."
    fi
    return $RETVAL
}

stop () {
    # Stop daemon
    echo -n "Stopping solr..."

    daemon --stop --name=$PROG  --verbose
    RETVAL=$?

    if [ $RETVAL = 0 ]
    then
        echo "Done."
    else
        echo "Failed. See error code for more information."
    fi
    return $RETVAL
}


restart () {
    daemon --restart --name=$PROG  --verbose
}


status () {
    # Report on the status of the daemon
    daemon --running --verbose --name=$PROG
    return $?
}


case "$1" in
    start)
        start
    ;;
    status)
        status
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    *)
        echo $"Usage: solr {start|status|stop|restart}"
        exit 3
    ;;
esac

exit $RETVAL