#!/bin/bash

source $HOME/.bash_profile

NODE=/usr/bin/node
DIRECTORY=gazetteer
COMMAND=$HOME/$DIRECTORY/deploy/schedule_provisioning
TOUCH=/bin/touch
TOUCHED_FILE=$HOME/touched/touched

if [ -f $TOUCH_DIRECTORY/touched ]; then
   rm $TOUCHED_FILE
   $COMMAND
fi